service: fake-krypto-node

provider:
  name: kubeless
  runtime: nodejs8
  namespace: kubeless
  environment :
    FAKE_KRYTPO_URL: ${self:custom.${self:custom.stage}.FAKE_KRYPTO_URL}

package:
  excludeDevDependencies: true
  exclude:
    - test/**
    - node_modules/**

functions:
  fake-krypto:
    handler: fake-krypto.fakeKrypto
    events:
      - http : POST fake-krypto
    environment:
      - name: FAKE_KRYPTO_URL
        value: 'http://fake-krypto:3000'

custom:
  stage: ${opt:stage, self:provider.stage}
  dev:
    FAKE_KRYTPO_URL: ${env:FAKE_KRYPTO_URL, 'http://localhost:3000/fake-krypto'}
  docker :
    FAKE_KRYTPO_URL: ${env:FAKE_KRYPTO_URL, 'http://localhost:3000/fake-krypto'}

plugins:
  - serverless-offline
  - serverless-kubeless
